---

# This is the normal playbook

- name: Prep system
  hosts: all
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Apt update and upgrade
      apt:
        update_cache: yes
        upgrade: yes

- name: Base role
  hosts: all
  connection: local
  become: yes
  become_user: root
  vars:
    ssh_host_key_files:
      - /etc/ssh/ssh_host_rsa_key
      - /etc/ssh/ssh_host_ed25519_key
    ssh_host_key_algorithms:
      - ssh-ed25519
      - ssh-rsa
    ssh_client_host_key_algorithms:
      - ssh-ed25519
      - ssh-rsa
    ssh_allow_groups: "{{ sshd_allowed_ssh_users_group }}"
    ssh_print_motd: yes
    ssh_print_pam_motd: yes
    sshd_moduli_minimum: "{{ sshd_moduli_size }}"
    ssh_ciphers:
      - chacha20-poly1305@openssh.com
      - aes256-gcm@openssh.com
      - aes128-gcm@openssh.com
      - aes256-ctr
      - aes192-ctr
      - aes128-ctr
    ssh_kex:
      - curve25519-sha256@libssh.org
      - diffie-hellman-group-exchange-sha256
    ssh_macs:
      - hmac-sha2-512-etm@openssh.com
      - hmac-sha2-256-etm@openssh.com
      - umac-128-etm@openssh.com
      - hmac-sha2-512
      - hmac-sha2-256
      - umac-128@openssh.com 
  collections:
    - devsec.hardening
  roles:
    - base
    - ssh_hardening
