---

users:
  - name: "hax"
    home_dir: "/home/hax"
    append_groups: yes
    pubkeys_from_github_user: haxwithaxe
    pubkeys_from_urls:
      - "https://<my local gitea server>/haxwithaxe/pubkeys/raw/branch/main/automation"
    ssh_user: yes
    no_password: yes
    sudo_no_password: yes
  - name: "root"
    home_dir: "/root"

required_groups:
  - name: ssh-users
  - name: docker
    gid: 998
    system: yes

no_passwords: yes
sshd_allowed_ssh_users_group: ssh-users
sshd_moduli_size: 2048
sshd_rsa_host_key_size: 8192

apt_no_recommends: no
apt_no_suggests: yes

