---

- name: Set group variables
  set_fact:
    _gid: "{{ item.gid | default(-1) }}"
    _system: "{{ item.system | default(false) }}"

- name: Add group with GID
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | int }}"
    system: "{{ item.system | default(false) }}"
    state: present
  when: item.gid is defined

- name: Add group without GID
  group:
    name: "{{ item.name }}"
    system: "{{ item.system | default(false) }}"
    state: present
  when: item.gid is not defined
